import type { SkillDefinition } from "../../shared/types";

/**
 * 20 built-in skills covering the high-leverage workflows from the spec. Each
 * skill is a curated procedure: trigger phrases, ordered instructions, the
 * tool subset it should use, and an output format.
 *
 * The agent runner injects the matching skill's `instructions[]` and
 * `workflow[]` into the system prompt, then constrains the available tools to
 * `allowedTools` for that turn.
 */
export const BUILT_IN_SKILLS: SkillDefinition[] = [
  {
    id: "nexus.add-feature",
    name: "Add Feature",
    description: "Implement a new feature: explore code, design, write tests, write code, run, summarize.",
    triggers: ["add feature", "implement", "build a", "create a feature", "добавь фичу", "реализуй"],
    instructions: [
      "Locate where the new feature belongs by reading nearby modules and entry points.",
      "Outline the design in 5–10 bullet points before changing code.",
      "Write a failing test that captures the expected behavior, then make it pass.",
      "Run the build and existing test suite at the end; fix any breakage.",
      "Summarize the change with file paths and rationale.",
    ],
    workflow: ["explore → plan → tests → code → run → summarize"],
    allowedTools: [
      "read_file", "list_files", "search_files", "grep",
      "write_file", "edit_file", "create_file", "rename_file",
      "run_terminal_command",
      "get_git_status", "get_git_diff",
    ],
    outputFormat: "diff + summary",
    safetyConstraints: ["never delete unrelated files", "never run destructive shell commands"],
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.fix-bug",
    name: "Fix Bug",
    description: "Reproduce a bug, locate the root cause, fix it, and add a regression test.",
    triggers: ["fix bug", "fix the bug", "bug", "error", "exception", "крашится", "ошибка"],
    instructions: [
      "Reproduce the bug from a log, stack trace, or failing test before fixing.",
      "Trace the cause to the root — do not patch symptoms.",
      "Fix the root cause and add a regression test that fails on `main` but passes on the branch.",
      "Run the affected test file; then the full suite if it is fast.",
    ],
    workflow: ["reproduce → locate → fix → test → verify"],
    allowedTools: [
      "read_file", "list_files", "search_files", "grep",
      "write_file", "edit_file", "create_file",
      "run_terminal_command",
      "get_git_diff", "get_git_status",
    ],
    outputFormat: "diff + summary + regression test",
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.refactor",
    name: "Refactor",
    description: "Refactor code without changing observable behavior; tests must stay green.",
    triggers: ["refactor", "clean up", "rewrite", "extract", "rename"],
    instructions: [
      "Identify the unit being refactored and its callers.",
      "List concrete steps in order before mutating files.",
      "Make small, behavior-preserving edits and re-run tests after each.",
      "Avoid changing public APIs unless the user requested it.",
    ],
    workflow: ["scope → plan → small edits → test"],
    allowedTools: [
      "read_file", "list_files", "search_files", "grep",
      "write_file", "edit_file", "rename_file",
      "run_terminal_command",
      "get_git_diff",
    ],
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.explain-code",
    name: "Explain Code",
    description: "Walk through a file or function and explain what it does, callers, and gotchas.",
    triggers: ["explain", "what does this", "walk me through", "объясни"],
    instructions: [
      "Read the target file fully; then read its imports' definitions where helpful.",
      "Produce a top-down explanation: purpose → main entry points → control flow → side effects.",
      "Call out any non-obvious invariants or gotchas with file:line references.",
    ],
    allowedTools: ["read_file", "list_files", "grep", "search_files"],
    outputFormat: "markdown explanation with file:line citations",
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.write-tests",
    name: "Write Tests",
    description: "Add unit/integration tests for an existing function or module.",
    triggers: ["write tests", "add tests", "unit test", "integration test", "напиши тесты"],
    instructions: [
      "Read the target unit and its existing test files (if any).",
      "Cover: happy path, common edge cases, error paths.",
      "Use the project's existing test runner and conventions — do not introduce new frameworks.",
      "Run the new tests and ensure they pass.",
    ],
    workflow: ["read → plan cases → write tests → run → fix"],
    allowedTools: [
      "read_file", "list_files", "search_files", "grep",
      "write_file", "edit_file", "create_file",
      "run_terminal_command",
    ],
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.review-pr",
    name: "Review PR / Diff",
    description: "Review the staged or branch diff and produce structured review comments.",
    triggers: ["review", "code review", "pr review", "ревью"],
    instructions: [
      "Read the diff fully (`get_git_diff`) and the surrounding files where context is needed.",
      "Group findings by: bug, security, performance, style, design, tests.",
      "Provide concrete file:line citations.",
      "Suggest follow-up actions; do not modify code.",
    ],
    allowedTools: ["read_file", "grep", "list_files", "get_git_diff", "get_git_status"],
    outputFormat: "structured review (bug / security / perf / style / design / tests)",
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.optimize-performance",
    name: "Optimize Performance",
    description: "Profile a hotspot and propose / apply targeted optimizations.",
    triggers: ["optimize", "performance", "slow", "perf", "ускорь"],
    instructions: [
      "Identify the hot path with profiling output, benchmarks, or code reading.",
      "Measure before changing — write or update a micro-bench if reasonable.",
      "Apply minimal, focused changes; re-measure to confirm.",
      "Avoid premature optimization elsewhere.",
    ],
    allowedTools: [
      "read_file", "search_files", "grep",
      "edit_file", "write_file",
      "run_terminal_command",
    ],
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.write-docs",
    name: "Write Documentation",
    description: "Write or update README / docs / docstrings for a module.",
    triggers: ["write docs", "documentation", "readme", "docstring", "документация"],
    instructions: [
      "Read the relevant source to understand current behavior.",
      "Update README / docs / inline comments to match.",
      "Use code blocks for examples; keep them runnable.",
      "Keep tone matching the existing docs.",
    ],
    allowedTools: ["read_file", "list_files", "search_files", "grep", "write_file", "edit_file", "create_file"],
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.api-design",
    name: "API Design",
    description: "Design a public API: types, errors, idiomatic shape, examples.",
    triggers: ["design api", "api design", "interface", "public api"],
    instructions: [
      "List the consumer's use cases first, then derive the API.",
      "Specify: types, errors, return contracts, breaking-change concerns.",
      "Provide 2–3 usage examples in code blocks.",
    ],
    allowedTools: ["read_file", "search_files", "grep"],
    outputFormat: "design doc with types and examples",
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.security-audit",
    name: "Security Audit",
    description: "Audit a file or module for common security issues.",
    triggers: ["security", "audit", "vulnerability", "owasp"],
    instructions: [
      "Look for: input validation gaps, secret handling, auth bypass, SSRF, injection, deserialization, path traversal, race conditions.",
      "Assume worst-case input; trace data flow from untrusted sources.",
      "Cite findings with file:line; rate severity (low/medium/high/critical).",
      "Do not modify code in this skill — produce findings only.",
    ],
    allowedTools: ["read_file", "search_files", "grep", "list_files"],
    outputFormat: "findings table (severity / file:line / description / fix)",
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.dependency-audit",
    name: "Dependency Audit",
    description: "Audit npm / pnpm / pip dependencies for security issues and outdated versions.",
    triggers: ["audit deps", "dependency audit", "outdated", "npm audit"],
    instructions: [
      "Inspect lockfile + manifest to enumerate dependencies.",
      "Run the project's audit command (`npm audit`, `pnpm audit`, `pip-audit`) when available.",
      "Group findings by severity; cite specific package@version.",
      "Suggest minimal-change upgrades.",
    ],
    allowedTools: ["read_file", "list_files", "run_terminal_command"],
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.git-commit",
    name: "Git Commit",
    description: "Stage selected files and write a clean conventional commit message.",
    triggers: ["commit", "git commit", "сделай коммит"],
    instructions: [
      "Inspect the working tree (`get_git_status`, `get_git_diff`).",
      "Stage only the files relevant to the change.",
      "Write a conventional commit subject (`feat:`, `fix:`, …) plus a body when needed.",
      "Never commit `.env`, `node_modules`, or other ignored paths.",
    ],
    allowedTools: ["get_git_status", "get_git_diff", "stage_files", "commit_changes"],
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.create-branch",
    name: "Create Git Branch",
    description: "Create a new branch with a sensible name for the current task.",
    triggers: ["new branch", "create branch", "checkout -b"],
    instructions: [
      "Pick a short, kebab-case branch name describing the task.",
      "Avoid long descriptions — at most 5 words.",
      "Switch to the branch immediately.",
    ],
    allowedTools: ["create_git_branch", "get_git_status"],
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.devops",
    name: "DevOps & CI",
    description: "Edit Dockerfiles, CI workflows, and deploy scripts; run validation locally.",
    triggers: ["docker", "ci", "github actions", "gitlab ci", "deploy", "kubernetes"],
    instructions: [
      "Read the existing CI / Docker config before editing.",
      "Make minimal additive changes; never remove an existing job without explanation.",
      "Validate locally where possible (`docker build --no-cache .`, `actionlint`, etc.).",
    ],
    allowedTools: [
      "read_file", "list_files", "search_files",
      "write_file", "edit_file", "create_file",
      "run_terminal_command",
    ],
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.migrate-db",
    name: "Database Migration",
    description: "Author a new database migration that is reversible and tested.",
    triggers: ["migration", "schema migration", "alembic", "prisma migrate", "knex migration"],
    instructions: [
      "Read the existing migrations and ORM schema to match conventions.",
      "Write a forward + reverse migration when the framework supports it.",
      "Verify the migration runs cleanly on a fresh database (when one is available).",
      "Never `DROP TABLE` without an explicit user request.",
    ],
    allowedTools: ["read_file", "list_files", "write_file", "create_file", "run_terminal_command"],
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.frontend-component",
    name: "Frontend Component",
    description: "Build a React/Vue/Svelte component matching project conventions and design tokens.",
    triggers: ["component", "react component", "vue component", "svelte component"],
    instructions: [
      "Match the project's framework, file layout, and styling system (tailwind / css modules / styled).",
      "Add prop types and a default export only when the project does that.",
      "Add a story or example file if the project has Storybook.",
    ],
    allowedTools: ["read_file", "list_files", "grep", "write_file", "edit_file", "create_file"],
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.api-endpoint",
    name: "API Endpoint",
    description: "Add a new HTTP endpoint with input validation, error handling, and a test.",
    triggers: ["api endpoint", "rest endpoint", "graphql resolver", "fastapi route", "express route"],
    instructions: [
      "Match the framework's existing route registration and error format.",
      "Validate every input; never trust the request body.",
      "Add a test exercising happy path + at least one error path.",
    ],
    allowedTools: [
      "read_file", "list_files", "grep",
      "write_file", "edit_file", "create_file",
      "run_terminal_command",
    ],
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.bench",
    name: "Microbenchmark",
    description: "Write a microbenchmark for a function and compare two implementations.",
    triggers: ["benchmark", "microbench", "perf compare"],
    instructions: [
      "Use the project's existing bench framework when available.",
      "Run the bench multiple times to reduce noise; report median + variance.",
      "Compare exactly two implementations at a time.",
    ],
    allowedTools: ["read_file", "list_files", "write_file", "create_file", "run_terminal_command"],
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.localize",
    name: "Localize",
    description: "Add i18n strings and update existing translations.",
    triggers: ["localize", "i18n", "translation", "перевести"],
    instructions: [
      "Read the existing translation files to learn the format and key naming.",
      "Add keys in every locale file the project ships; use English fallback for new locales.",
      "Never delete existing keys.",
    ],
    allowedTools: ["read_file", "list_files", "search_files", "grep", "write_file", "edit_file", "create_file"],
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
  {
    id: "nexus.notebook-cleanup",
    name: "Notebook Cleanup",
    description: "Clean up a Jupyter notebook: clear outputs, fix imports, refactor messy cells.",
    triggers: ["notebook", "jupyter", "ipynb"],
    instructions: [
      "Identify dead cells and merge fragmented ones.",
      "Move imports to a single cell at the top; remove duplicates.",
      "Do not run cells unless explicitly asked.",
    ],
    allowedTools: ["read_file", "list_files", "edit_file", "write_file"],
    builtIn: true,
    enabled: true,
    source: "built-in",
  },
];
